### ISSUE TITLE
ISP Spectrum Returns "Unknown ISP" message

### ISSUE THREAD

**Issue by x-15a2** [librespeed/speedtest#592]
## Description
When running LibreSpeed from Windows 10, ISP Spectrum returns message "Unknown ISP". 

## Server
New York, United States (2) (Cloudvider)
https://librespeed.org 

## Client
Windows 10 with browsers: (All tested with clean user profiles)
- Vivaldi
- Firefox
- Edge 

No VPN

## Steps to reproduce
* Go to https://librespeed.org
* Click Start button
* ISP = "Unknown ISP"
NOTE: https://ipinfo.io correctly identifies the ISP as Spectrum/AS10796 Charter Communications Inc

## Expected behaviour
Should have identified ISP as Spectrum or AS10796 Charter Communications Inc

## Screenshots
If necessary, add screenshots of the test.

F12 > Network screenshots can be particularly useful
![image](https://github.com/librespeed/speedtest/assets/6061680/2c9b3ccf-e32f-4d7d-b12e-1e458ff4e538)

**Comment by sstidl** [comment]
This should be fixed if the owner of the server updates to 5.3

**Comment by x-15a2** [comment]
Thanks. I had tried on a few servers, with the same result. Today I went through all servers that are available to me and only the Tokyo, Japan (A573) returned my ISP (as Charter Communications Inc, US). I guess the other servers are in need of the update.

Thanks!

**Comment by sstidl** [comment]
Sorry to tell  you that I can't reproduce. When I use the Tokyo server it shows the correct result for my IP address

**Comment by x-15a2** [comment]
Interesting, and thanks for looking into this. Here are the results that I get: 
![image](https://github.com/librespeed/speedtest/assets/6061680/12b43dc5-8381-4c05-a6b1-a7c4a4cfa3ae)

The Tokyo server used to identify my ISP as Charter Communication, but now I get unknown ISP, as with all the other LibreSpeed servers. 

I've tested the IPINFO API, using IPINFO.IO and it returns the correct ASN. Could the API key be corrupt, or is a 429 error being returned due to too many requests?

**Comment by x-15a2** [comment]
> Sorry to tell you that I can't reproduce. When I use the Tokyo server it shows the correct result for my IP address

So... are there any additional details that I can provide to try to get this corrected? There's no way (that I've found) to know what version a specific service is on version 5.3 or not. I'm glad that it works for you, but that doesn't resolve the issue. I've supplied add'l details above and have asked for some add'l information, but there has been no response to that, only a comment similar to "it works on my machine".

**Comment by abdullahdevrel** [comment]
IPinfo DevRel here. I pitched the idea to move from IPinfo's API based system to IPinfo's [free IP to Country ASN database](https://ipinfo.io/products/free-ip-database): https://github.com/librespeed/speedtest/issues/641

I have seen this issue happen a couple of times, and I think it is due to some networking issues. I believe that if the project moves to the IP database solution, it could reduce network-related issues as the project will be calling the database within the local machine.

Even though we do not require an access token to make call to our API. In fact we permit 1,000 request per day without an access token. But the best option, in my opinion, is opting for the free IP database.

**Comment by x-15a2** [comment]
@sstidl Any thoughts on implementing @abdullahdevrel 's above suggestion? My thought is that the 1,000 requests per day are quickly exceeded and there's either no access token or the token has expired. Your thoughts?

Again, this is when running from https://librespeed.org and not from a self-hosted server.

**Comment by sstidl** [comment]
This was implemented in 5.4.0

**Comment by x-15a2** [comment]
Thanks, I appreciate this. I found it working on 2 servers (Serbia SOX and Amsterdam Rust Backend). 
Just a though (let me know if a new issue should be created for this...) would it be possible to include the version that the server is running? Example:

![LSProto](https://github.com/user-attachments/assets/a9ad70f7-ce24-4ba0-9138-c424181bd246)
